// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {ERC20Mock} from "@openzeppelin/contracts/mocks/token/ERC20Mock.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IConverter} from "../src/market/IConverter.sol";
import {BasketRegistry} from "../src/market/BasketRegistry.sol";
import {HolderDistributor, IBasketRegistry} from "../src/market/HolderDistributor.sol";

/// Same 1:1 mint-on-convert stand-in as HolderDistributor.t.sol, so what an epoch reserves equals what
/// its legs spent — which is the assumption keeper/holder-airdrop/make-fixture.mjs builds the fixture on.
contract FixtureConverter is IConverter {
    IERC20 public immutable usdg;
    mapping(address => bool) public supported;

    constructor(IERC20 usdg_) {
        usdg = usdg_;
    }

    function setSupported(address t, bool v) external {
        supported[t] = v;
    }

    function isSupported(address t) external view returns (bool) {
        return supported[t];
    }

    function convert(uint256 amountIn, address targetToken, address recipient) external returns (uint256 out) {
        usdg.transferFrom(msg.sender, address(this), amountIn);
        out = amountIn;
        ERC20Mock(targetToken).mint(recipient, out);
    }
}

/// The keeper is off-chain, so nothing in Solidity would otherwise catch a JS-side change to the leaf
/// encoding, the pair hash or the tree shape — the root would simply stop matching any proof a holder
/// presents, and only in production. This replays a root built entirely by the keeper
/// (test/fixtures/holder-airdrop-root.json, regenerated by keeper/holder-airdrop/make-fixture.mjs)
/// through the real distributor: every leaf, every proof, every claim, and the reserved cap.
contract HolderAirdropRootTest is Test {
    ERC20Mock usdg;
    FixtureConverter conv;
    BasketRegistry reg;
    HolderDistributor dist;

    address governor = address(this);
    address keeper = address(0x11111);
    address floorSink = address(0xF100);
    address slashSink = address(0x5145);

    uint256 constant REG_TIMELOCK = 2 days;
    uint256 constant MIN_EPOCH_INTERVAL = 12 hours;
    uint256 constant CHALLENGE_WINDOW = 6 hours;
    uint256 constant CLAIM_WINDOW = 90 days;
    uint256 constant KEEPER_GRACE = 24 hours;
    uint256 constant MIN_BOND = 1 ether;

    string json;
    bytes32 root;
    uint256 epoch;
    uint256 claimCount;
    address[] stocks;

    function setUp() public {
        json = vm.readFile("test/fixtures/holder-airdrop-root.json");
        root = vm.parseJsonBytes32(json, ".root");
        epoch = vm.parseJsonUint(json, ".epoch");
        claimCount = vm.parseJsonUint(json, ".claimCount");
        stocks = vm.parseJsonAddressArray(json, ".stocks");

        vm.warp(1_000_000);
        usdg = new ERC20Mock();
        conv = new FixtureConverter(IERC20(address(usdg)));
        reg = new BasketRegistry(IConverter(address(conv)), governor, REG_TIMELOCK);

        for (uint256 i = 0; i < stocks.length; i++) {
            deployCodeTo("ERC20Mock.sol:ERC20Mock", stocks[i]);
            conv.setSupported(stocks[i], true);
            reg.proposeStock(stocks[i]);
        }
        vm.warp(block.timestamp + REG_TIMELOCK);
        for (uint256 i = 0; i < stocks.length; i++) {
            reg.commitStock(stocks[i]);
        }

        dist = new HolderDistributor(
            IERC20(address(usdg)),
            IConverter(address(conv)),
            IBasketRegistry(address(reg)),
            floorSink,
            slashSink,
            governor,
            keeper,
            MIN_EPOCH_INTERVAL,
            CHALLENGE_WINDOW,
            CLAIM_WINDOW,
            KEEPER_GRACE,
            MIN_BOND
        );
        usdg.mint(address(dist), vm.parseJsonUint(json, ".usdgPot"));
        vm.deal(keeper, 10 ether);
        vm.prank(keeper);
        dist.postBond{value: MIN_BOND}();
    }

    // -------------------------------------------------------------- helpers

    function _claim(uint256 i)
        internal
        view
        returns (address holder, address token, uint256 amount, bytes32 leaf, bytes32[] memory proof)
    {
        string memory at = string.concat(".claims[", vm.toString(i), "]");
        holder = vm.parseJsonAddress(json, string.concat(at, ".holder"));
        token = vm.parseJsonAddress(json, string.concat(at, ".token"));
        amount = vm.parseJsonUint(json, string.concat(at, ".amount"));
        leaf = vm.parseJsonBytes32(json, string.concat(at, ".leaf"));
        proof = vm.parseJsonBytes32Array(json, string.concat(at, ".proof"));
    }

    function _runEpoch() internal returns (uint256 posted) {
        uint256 legs = stocks.length;
        for (uint256 i = 0; i < legs; i++) {
            string memory at = string.concat(".buys[", vm.toString(i), "]");
            vm.prank(keeper);
            dist.settleBuy(
                vm.parseJsonAddress(json, string.concat(at, ".token")),
                vm.parseJsonUint(json, string.concat(at, ".usdg"))
            );
        }
        vm.warp(block.timestamp + MIN_EPOCH_INTERVAL);
        vm.prank(keeper);
        posted = dist.postRoot(root);
        vm.warp(block.timestamp + CHALLENGE_WINDOW);
    }

    // -------------------------------------------------------------- parity

    /// The keeper's leaf encoding must equal the contract's, byte for byte, or every proof is worthless.
    function test_KeeperLeafEncodingMatchesTheContract() public view {
        for (uint256 i = 0; i < claimCount; i++) {
            (address holder, address token, uint256 amount, bytes32 leaf,) = _claim(i);
            assertEq(dist.leafOf(epoch, holder, token, amount), leaf, "keeper leaf != contract leafOf");
        }
    }

    /// Every proof the keeper published verifies against the root it published, inside the real contract.
    function test_EveryKeeperProofClaimsItsExactAmount() public {
        uint256 posted = _runEpoch();
        assertEq(posted, epoch, "fixture epoch is not the epoch the root finalized");
        for (uint256 i = 0; i < claimCount; i++) {
            (address holder, address token, uint256 amount,, bytes32[] memory proof) = _claim(i);
            uint256 before = ERC20Mock(token).balanceOf(holder);
            vm.prank(holder);
            dist.claim(epoch, token, amount, proof);
            assertEq(ERC20Mock(token).balanceOf(holder) - before, amount, "holder was not paid the leaf amount");
        }
    }

    /// The keeper's allocation must consume the epoch EXACTLY: no leaf refused for over-attribution, and
    /// nothing stranded that the floor sweep has to mop up.
    function test_AllocationConsumesTheEpochExactly() public {
        _runEpoch();
        for (uint256 i = 0; i < claimCount; i++) {
            (address holder, address token, uint256 amount,, bytes32[] memory proof) = _claim(i);
            vm.prank(holder);
            dist.claim(epoch, token, amount, proof);
        }
        for (uint256 i = 0; i < stocks.length; i++) {
            assertEq(dist.claimable(epoch, stocks[i]), 0, "epoch left unclaimed stock");
            assertEq(ERC20Mock(stocks[i]).balanceOf(address(dist)), 0, "distributor still holds stock");
        }
    }

    /// The two-snapshot gate is off-chain, so this is the on-chain half of the proof: a wallet the gate
    /// excluded has no leaf at all, and therefore cannot construct a claim against this root.
    function test_ExcludedWalletsHaveNoClaimableLeaf() public {
        _runEpoch();
        address[] memory excluded = vm.parseJsonAddressArray(json, ".excluded");
        for (uint256 i = 0; i < claimCount; i++) {
            (address holder,,,,) = _claim(i);
            for (uint256 j = 0; j < excluded.length; j++) {
                assertTrue(holder != excluded[j], "an excluded wallet was given a leaf");
            }
        }
        // and a hand-made leaf for one of them does not verify against the published root
        bytes32[] memory empty = new bytes32[](0);
        vm.prank(excluded[0]);
        vm.expectRevert(HolderDistributor.BadProof.selector);
        dist.claim(epoch, stocks[0], 1, empty);
    }

    /// A proof that belongs to a different leaf must not be reusable by anyone else.
    function test_ProofsAreNotTransferableBetweenHolders() public {
        _runEpoch();
        (address holder0, address token0, uint256 amount0,, bytes32[] memory proof0) = _claim(0);
        address other;
        for (uint256 i = 1; i < claimCount && other == address(0); i++) {
            (address candidate,,,,) = _claim(i);
            if (candidate != holder0) other = candidate;
        }
        assertTrue(other != address(0), "fixture needs two distinct holders");
        vm.prank(other);
        vm.expectRevert(HolderDistributor.BadProof.selector);
        dist.claim(epoch, token0, amount0, proof0);
    }
}
