// Regenerates test/fixtures/holder-airdrop-root.json — the shared artifact that pins the keeper's leaf
// encoding, tree shape and allocation against the REAL contract in test/HolderAirdropRoot.t.sol. Run it
// after any change to merkle.mjs, allocate.mjs or eligibility.mjs:
//
//   node keeper/holder-airdrop/make-fixture.mjs
//
// The scenario is deliberately adversarial: a flash farmer, a seller, a wallet exactly on the bar, one a
// wei under it, and an excluded pool wallet — so a regression in the gate changes the fixture and the
// Solidity test fails loudly rather than the numbers quietly shifting.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getAddress } from "viem";
import { buildManifest, planEpoch, proofsFor } from "./manifest.mjs";
import { leafHash } from "./merkle.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "test", "fixtures", "holder-airdrop-root.json");

const AAPL = getAddress("0x000000000000000000000000000000000000AAa1");
const NVDA = getAddress("0x000000000000000000000000000000000000bB02");
const DISTRIBUTOR = getAddress("0x00000000000000000000000000000000000d1547");
const ESSEY = getAddress("0x315790B57C19141B34C4653a91b096Cf3f071610");

const HOLD = getAddress("0x0000000000000000000000000000000000000A11"); // steady holder
const BUYER = getAddress("0x0000000000000000000000000000000000000b22"); // added between snapshots
const SELLER = getAddress("0x0000000000000000000000000000000000000C33"); // sold between snapshots, prefers basket 1
const FARMER = getAddress("0x0000000000000000000000000000000000000d44"); // absent at prev — the snapshot-farming attack
const ATBAR = getAddress("0x0000000000000000000000000000000000000E55"); // exactly at the bar
const UNDER = getAddress("0x0000000000000000000000000000000000000f66"); // one wei under the bar
const POOL = getAddress("0x0000000000000000000000000000000000000999"); // excluded venue wallet

const BAR = (8_888_888_888n * 10n ** 18n) / 1_000n;
const USDG_POT = 1_000_000_000_000n; // 1,000,000 USDG at 6 decimals

const baskets = new Map([
  [0, { tokens: [AAPL, NVDA], bps: [6_000, 4_000] }],
  [1, { tokens: [NVDA], bps: [10_000] }],
]);

const prev = {
  block: 100n,
  balances: new Map([
    [HOLD, BAR * 20n],
    [BUYER, BAR * 5n],
    [SELLER, BAR * 50n],
    [ATBAR, BAR],
    [UNDER, BAR - 1n],
    [POOL, BAR * 10_000n],
  ]),
};

const curr = {
  block: 200n,
  balances: new Map([
    [HOLD, BAR * 20n],
    [BUYER, BAR * 50n],
    [SELLER, BAR * 5n],
    [FARMER, BAR * 100n],
    [ATBAR, BAR],
    [UNDER, BAR - 1n],
    [POOL, BAR * 10_000n],
  ]),
};

const inputs = {
  prev,
  curr,
  barWei: BAR,
  exclusions: [POOL],
  preferences: new Map([[SELLER, 1]]),
  baskets,
  defaultBasketId: 0,
  usdgPot: USDG_POT,
};

const plan = planEpoch(inputs);
// MockConverter mints 1:1 (test/HolderDistributor.t.sol:36-39), so what the epoch reserves equals what
// each leg spends. The Solidity test calls settleBuy with exactly these amounts.
const reserved = new Map(plan.buys.map((b) => [b.token, b.usdg]));

const { manifest } = buildManifest({
  ...inputs,
  chainId: 4663,
  distributor: DISTRIBUTOR,
  token: ESSEY,
  epoch: 0n,
  reserved,
});

const holders = [HOLD, BUYER, SELLER, FARMER, ATBAR, UNDER, POOL];
const claims = holders.flatMap((h) =>
  proofsFor(manifest, h).map((c) => ({
    holder: h,
    token: c.token,
    amount: c.amount,
    leaf: leafHash({ epoch: 0n, holder: h, token: c.token, amount: BigInt(c.amount) }),
    proof: c.proof,
  })),
);

const fixture = {
  note: "generated by keeper/holder-airdrop/make-fixture.mjs — do not hand-edit",
  stocks: [AAPL, NVDA],
  epoch: manifest.epoch,
  root: manifest.root,
  barWei: String(BAR),
  usdgPot: String(USDG_POT),
  excluded: [FARMER, UNDER, POOL],
  buys: plan.buys.map((b) => ({ token: b.token, usdg: String(b.usdg) })),
  claimCount: claims.length,
  claims,
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(fixture, null, 2)}\n`);
console.log(`wrote ${OUT}`);
console.log(`root ${manifest.root}  ${claims.length} claims  ${plan.buys.length} buy legs`);
