package poseidon

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/groth16"
	groth16bn254 "github.com/consensys/gnark/backend/groth16/bn254"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
)

// TestExportOnchainVerifier produces the on-chain verifier: a real Groth16 proof of a real solvency
// statement, the Solidity verifier generated from its vk, and the proof/public-input calldata. The
// companion script deploys the verifier to a local EVM and confirms it verifies on-chain (the ~2 ms
// / few-hundred-k-gas check that happens on every settlement chain). The portable-proof verifier is
// generated by the identical vk.ExportSolidity — its on-chain cost is dominated by the number of
// public inputs (loan commitments) + the fixed pairing, NOT the 2.4M circuit size.
//
//	OUT=<dir> go test -run TestExportOnchainVerifier   # writes Verifier.sol, proof.txt, input.txt
func TestExportOnchainVerifier(t *testing.T) {
	out := os.Getenv("OUT")
	if out == "" {
		out = t.TempDir()
	}
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &SolvencyCircuit{})
	if err != nil {
		t.Fatal(err)
	}
	pk, vk, err := groth16.Setup(ccs)
	if err != nil {
		t.Fatal(err)
	}
	terms := sampleTerms(1000)
	c := commit(t, terms)
	full, err := frontend.NewWitness(assign(terms, c), ecc.BN254.ScalarField())
	if err != nil {
		t.Fatal(err)
	}
	proof, err := groth16.Prove(ccs, pk, full)
	if err != nil {
		t.Fatal(err)
	}
	pub, err := full.Public()
	if err != nil {
		t.Fatal(err)
	}
	if err := groth16.Verify(proof, vk, pub); err != nil {
		t.Fatalf("off-chain sanity verify: %v", err)
	}

	// Solidity verifier from the vk.
	f, err := os.Create(filepath.Join(out, "Verifier.sol"))
	if err != nil {
		t.Fatal(err)
	}
	if err := vk.ExportSolidity(f); err != nil {
		t.Fatal(err)
	}
	f.Close()

	// proof -> uint256[8] calldata; solvency has no gnark commitments, so it is exactly 8 words.
	sol := proof.(*groth16bn254.Proof).MarshalSolidity()
	if len(sol) != 8*32 {
		t.Fatalf("expected 8-word proof, got %d bytes (circuit introduced commitments)", len(sol))
	}
	words := make([]string, 8)
	for i := 0; i < 8; i++ {
		words[i] = "0x" + hex.EncodeToString(sol[i*32:i*32+32])
	}
	os.WriteFile(filepath.Join(out, "proof.txt"), []byte(strings.Join(words, ",")), 0644)
	os.WriteFile(filepath.Join(out, "input.txt"), []byte(c.String()), 0644)

	t.Logf("wrote Verifier.sol + proof.txt + input.txt to %s", out)
	t.Logf("public input (loan commitment): %s", c.String())
}
