// Generate src/docs.generated.ts from the repo docs so the site can render them (self-contained).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS = join(HERE, "..", "..", "docs");

// Visitor-facing docs, grouped for the reading room. CURATION RULE (founder, 2026-08): only docs that
// serve the current Market-layer narrative appear here — prior iterations' docs stay in the repo but
// off the page. The audit trail is the exception: every published round stays, clean or not, because
// fix-first transparency transcends any single narrative.
// `file` is relative to /docs and doubles as the GitHub source link, so every card in the site can
// point at the exact file it renders — no separately-maintained list to drift out of sync.
const PICK = [
  ["The Market", "THE-MARKET.md", "The Market layer — design", "Seats, Vaults, Tiers, the Bell, the Exchange, Notes, Cases — every mechanic, why it's shaped that way, and what's enforced vs designed."],
  ["The Market", "TOKENOMICS.md", "$ESSEY tokenomics", "Three assets, three jobs, never crossed. Fixed supply, no emissions, free mint, three fee engines ranked by durability — and how it fails, stated plainly."],
  ["The Market", "DESIGN-whitelist-onboarding.md", "Earning a Seat — the whitelist", "The testnet trading-day quest: earn a free mint by using the protocol, committed on-chain as a timelocked Merkle root anyone can recompute."],
  ["The engine", "SCOPE-robinhood-chain.md", "Robinhood Chain scope", "The lending engine underneath: real Stock Tokens, Chainlink feeds, and what the chain does and doesn't give us."],
  ["The engine", "LTV-RISK-FRAMEWORK.md", "LTV & risk framework", "How loan-to-value limits are chosen per asset from a stress model."],
  ["The engine", "INTEREST-RATE-MODEL.md", "Interest rate model", "How supply/borrow rates are set by utilization to attract liquidity."],
  ["The engine", "OUTSTANDING.md", "Known-open items", "Everything we know is unfinished, including what blocks mainnet. Published deliberately."],
  ["Audits", "audits/README.md", "How we audit", "Independent agents attack every change; findings are published fix-first, clean or not."],
  ["Audits", "audits/market-layer-round-1.md", "Market layer — round 1", "Seats, Vaults, the Bell, the converter, Notes: the first adversarial gate on the game's contracts."],
  ["Audits", "audits/market-layer-round-2.md", "Market layer — round 2", "$ESSEY and the Exchange: one hardening applied, re-audit clean."],
  ["Audits", "audits/market-layer-round-3.md", "Market layer — round 3", "The mint distributor: two hardenings — including a deploy-unfixable defect the gate caught before it could ship."],
  ["Audits", "audits/sui-rounds-1-6.md", "Move / Sui — rounds 1–6", "66 confirmed findings across six adversarial rounds on an earlier iteration. No round came back clean."],
  ["Audits", "audits/solidity-round-1.md", "Solidity — round 1", "19 confirmed, 5 refuted against the lending engine. Not clean."],
];

// Founder rule (2026-08, strengthened): the site presents our design and tokenomics ON THEIR OWN
// MERITS — no competitor names AND no borrowed-provenance framing ("modeled on", "the reference
// protocol"). Internal modeling docs stay in the repo for engineering; the site renders standalone
// public docs instead, and the sanitizer + gate below are the backstop, not the plan.
const sanitize = (md) => md
  .replace(/stonkbrokers\.cash/gi, "the reference protocol's site")
  .replace(/Stonk\s?Brokers?'s/gi, "the reference protocol's")
  .replace(/Stonk\s?Brokers?'/gi, "the reference protocol's")
  .replace(/Stonk\s?Brokers?/gi, "the reference protocol")
  .replace(/Stonk(?=[A-Z])/g, "Ref") // their contract identifiers: StonkLoanVault -> RefLoanVault
  .replace(/(^|[.!?]\s+)the reference protocol/g, "$1The reference protocol"); // sentence starts

const missing = [];
const docs = PICK.map(([group, file, title, desc]) => {
  let md = "";
  try { md = sanitize(readFileSync(join(DOCS, file), "utf8")); } catch { missing.push(file); md = `# ${title}\n\n_(document unavailable)_`; }
  const slug = file.replace(/\.md$/, "").toLowerCase().replace(/\//g, "-");
  return { slug, group, file, title, desc, md };
});
// The rule is a hard gate, not a best effort: fail the build if any reference survives.
const leak = docs.filter((d) => /stonk|reference protocol/i.test(d.md));
if (leak.length) { console.error(`gen-docs: competitor reference leaked in ${leak.map((d) => d.file).join(", ")}`); process.exit(1); }
// A doc that silently renders as "(document unavailable)" is worse than a failed build — it ships
// a dead card to visitors. Fail loudly instead.
if (missing.length) { console.error(`gen-docs: MISSING ${missing.join(", ")}`); process.exit(1); }

const out = `// GENERATED by gen-docs.mjs — do not edit by hand.
export interface Doc { slug: string; group: string; file: string; title: string; desc: string; md: string }
export const DOCS: Doc[] = ${JSON.stringify(docs, null, 0)};
`;
writeFileSync(join(HERE, "src", "docs.generated.ts"), out);
console.log(`generated src/docs.generated.ts — ${docs.length} docs`);
