// Generate src/docs.generated.ts from the repo docs so the site can render them (self-contained).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS = join(HERE, "..", "..", "docs");

// Visitor-facing docs, grouped for the reading room (internal planning docs are skipped).
// `file` is relative to /docs and doubles as the GitHub source link, so every card in the site can
// point at the exact file it renders — no separately-maintained list to drift out of sync.
const PICK = [
  ["Protocol", "WHY-ESSEY-IS-DIFFERENT.md", "Why Essey is different", "How our lending differs from Aave/Kamino/Suilend — and what is actually enforced today."],
  ["Protocol", "ARCHITECTURE.md", "Architecture", "The four tiers: frontend, operator, on-chain program, and oracle."],
  ["Protocol", "SCOPE-robinhood-chain.md", "Robinhood Chain scope", "The Solidity port: real Stock Tokens, Chainlink feeds, and what the chain does and doesn't give us."],
  ["Risk", "LTV-RISK-FRAMEWORK.md", "LTV & risk framework", "How loan-to-value limits are chosen per asset from a stress model."],
  ["Risk", "INTEREST-RATE-MODEL.md", "Interest rate model", "How supply/borrow rates are set by utilization to attract liquidity."],
  ["Risk", "OUTSTANDING.md", "Known-open items", "Everything we know is unfinished, including what blocks mainnet. Published deliberately."],
  ["Audits", "audits/README.md", "How we audit", "Independent agents attack every change; findings are published fix-first, clean or not."],
  ["Audits", "audits/sui-rounds-1-6.md", "Move / Sui — rounds 1–6", "66 confirmed findings across six adversarial rounds. No round came back clean."],
  ["Audits", "audits/solidity-round-1.md", "Solidity — round 1", "19 confirmed, 5 refuted against the Robinhood Chain port. Not clean."],
  ["Audits", "AUDIT-2026-07-14-sui.md", "Security audit & pentest", "Adversarial review + penetration test — one critical bug found and fixed."],
  ["Audits", "EVIDENCE-2026-07-14.md", "Evidence", "On-chain proofs, the penetration test, and full end-to-end loans."],
];

const missing = [];
const docs = PICK.map(([group, file, title, desc]) => {
  let md = "";
  try { md = readFileSync(join(DOCS, file), "utf8"); } catch { missing.push(file); md = `# ${title}\n\n_(document unavailable)_`; }
  const slug = file.replace(/\.md$/, "").toLowerCase().replace(/\//g, "-");
  return { slug, group, file, title, desc, md };
});
// A doc that silently renders as "(document unavailable)" is worse than a failed build — it ships
// a dead card to visitors. Fail loudly instead.
if (missing.length) { console.error(`gen-docs: MISSING ${missing.join(", ")}`); process.exit(1); }

const out = `// GENERATED by gen-docs.mjs — do not edit by hand.
export interface Doc { slug: string; group: string; file: string; title: string; desc: string; md: string }
export const DOCS: Doc[] = ${JSON.stringify(docs, null, 0)};
`;
writeFileSync(join(HERE, "src", "docs.generated.ts"), out);
console.log(`generated src/docs.generated.ts — ${docs.length} docs`);
